[[7, 0, 1], 20.0, {"submitted": 1586341353.3990247, "started": 1586341353.4075584, "finished": 1586341353.430153}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 26, in compute\n    picked_conf_file = configselector() # External files usage: configselector.py and count.txt from hpbandster/core\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/configselector.py\", line 13, in configselector\n    count = int(count)\nValueError: invalid literal for int() with base 10: ''\n"]
[[0, 0, 0], 6.666666666666666, {"submitted": 1586341353.1595495, "started": 1586341353.1607492, "finished": 1586341421.3777723}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-18_cih/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-18_cih/referenceRealizedModeChoice.csv'\n"]
[[8, 0, 1], 6.666666666666666, {"submitted": 1586341421.3837035, "started": 1586341421.3843307, "finished": 1586343547.8534176}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-23_zvn/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-23_zvn/referenceRealizedModeChoice.csv'\n"]
[[1, 0, 0], 20.0, {"submitted": 1586341353.1836212, "started": 1586341353.19092, "finished": 1586343611.1449442}, {"loss": 79.78385240352065, "info": 79.78385240352065}, null]
[[6, 0, 2], 6.666666666666666, {"submitted": 1586341353.3766541, "started": 1586341353.380444, "finished": 1586343734.2388504}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-05_onc/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_10-23-05_onc/referenceRealizedModeChoice.csv'\n"]
[[1, 0, 1], 20.0, {"submitted": 1586341353.194888, "started": 1586341353.1982567, "finished": 1586343841.7562876}, {"loss": 159.30508474576268, "info": 159.30508474576268}, null]
[[2, 0, 0], 6.666666666666666, {"submitted": 1586341353.2085836, "started": 1586341353.210226, "finished": 1586343965.420079}, {"loss": 187.3183818551117, "info": 187.3183818551117}, null]
[[2, 0, 1], 6.666666666666666, {"submitted": 1586341353.220612, "started": 1586341353.222522, "finished": 1586343967.0726035}, {"loss": 187.3183818551117, "info": 187.3183818551117}, null]
[[3, 0, 0], 20.0, {"submitted": 1586341353.2497408, "started": 1586341353.2572289, "finished": 1586343988.5090573}, {"loss": 187.81629429022792, "info": 187.81629429022792}, null]
[[6, 0, 1], 6.666666666666666, {"submitted": 1586341353.3575726, "started": 1586341353.3660884, "finished": 1586344103.5559192}, {"loss": 151.42842626698842, "info": 151.42842626698842}, null]
[[5, 0, 1], 20.0, {"submitted": 1586341353.3332324, "started": 1586341353.3354785, "finished": 1586344342.25736}, {"loss": 46.524712254570076, "info": 46.524712254570076}, null]
[[5, 0, 0], 20.0, {"submitted": 1586341353.3194287, "started": 1586341353.3218293, "finished": 1586344391.4126384}, {"loss": 57.71496276235612, "info": 57.71496276235612}, null]
[[0, 0, 1], 6.666666666666666, {"submitted": 1586341353.1631994, "started": 1586341353.165346, "finished": 1586344418.516834}, {"loss": 57.76997291807719, "info": 57.76997291807719}, null]
[[4, 0, 2], 6.666666666666666, {"submitted": 1586341353.2998602, "started": 1586341353.3015022, "finished": 1586344424.2768753}, {"loss": 57.76997291807719, "info": 57.76997291807719}, null]
[[3, 0, 1], 20.0, {"submitted": 1586341353.2625988, "started": 1586341353.2656083, "finished": 1586344431.589259}, {"loss": 191.92792945565543, "info": 191.92792945565543}, null]
[[7, 0, 0], 20.0, {"submitted": 1586341353.3858902, "started": 1586341353.3948777, "finished": 1586344549.0327294}, {"loss": 184.87486712870444, "info": 184.87486712870444}, null]
[[8, 0, 0], 6.666666666666666, {"submitted": 1586341353.434102, "started": 1586341353.4347765, "finished": 1586344576.469283}, {"loss": 188.36238997968854, "info": 188.36238997968854}, null]
[[4, 0, 1], 6.666666666666666, {"submitted": 1586341353.2917004, "started": 1586341353.2944622, "finished": 1586344682.5270295}, {"loss": 184.87486712870444, "info": 184.87486712870444}, null]
[[0, 0, 2], 6.666666666666666, {"submitted": 1586341353.1772091, "started": 1586341353.1797273, "finished": 1586344718.9630845}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-18-11_wjl/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-18-11_wjl/referenceRealizedModeChoice.csv'\n"]
[[2, 0, 2], 6.666666666666666, {"submitted": 1586341353.2337234, "started": 1586341353.2375972, "finished": 1586344870.5209708}, {"loss": 187.71896863010608, "info": 187.71896863010608}, null]
[[6, 0, 0], 6.666666666666666, {"submitted": 1586341353.3506918, "started": 1586341353.3523316, "finished": 1586345245.2543545}, {"loss": 178.49109716805157, "info": 178.49109716805157}, null]
[[9, 0, 0], 20.0, {"submitted": 1586343611.1498773, "started": 1586343611.1507666, "finished": 1586345414.960432}, {"loss": 136.28469871360866, "info": 136.28469871360866}, null]
[[4, 0, 0], 6.666666666666666, {"submitted": 1586341353.2699938, "started": 1586341353.278956, "finished": 1586345591.9318845}, {"loss": 195.52045493125104, "info": 195.52045493125104}, null]
[[10, 0, 0], 6.666666666666666, {"submitted": 1586343841.763278, "started": 1586343841.7638085, "finished": 1586345867.7996185}, {"loss": 186.42292936131798, "info": 186.42292936131798}, null]
[[9, 0, 1], 20.0, {"submitted": 1586343734.2434897, "started": 1586343734.2443306, "finished": 1586345882.0942974}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-06-12_ylb/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-06-12_ylb/referenceRealizedModeChoice.csv'\n"]
[[10, 0, 1], 6.666666666666666, {"submitted": 1586343965.4243321, "started": 1586343965.4250026, "finished": 1586345985.2170398}, {"loss": 178.98713608666213, "info": 178.98713608666213}, null]
[[8, 0, 2], 6.666666666666666, {"submitted": 1586343547.8731904, "started": 1586343547.878854, "finished": 1586346104.0336072}, {"loss": 186.42292936131798, "info": 186.42292936131798}, null]
[[12, 0, 0], 6.666666666666666, {"submitted": 1586344342.26479, "started": 1586344342.2662084, "finished": 1586346476.8858464}, {"loss": 133.4537914691943, "info": 133.4537914691943}, null]
[[11, 0, 0], 20.0, {"submitted": 1586343988.5206952, "started": 1586343988.5215042, "finished": 1586346480.35603}, {"loss": 102.7085308056872, "info": 102.7085308056872}, null]
[[12, 0, 2], 6.666666666666666, {"submitted": 1586344418.5277066, "started": 1586344418.5290215, "finished": 1586346619.97353}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-13-58_eyv/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-13-58_eyv/referenceRealizedModeChoice.csv'\n"]
[[13, 0, 0], 20.0, {"submitted": 1586344424.2870986, "started": 1586344424.2886426, "finished": 1586346673.9420028}, {"loss": 154.54146919431278, "info": 154.54146919431278}, null]
[[14, 0, 1], 6.666666666666666, {"submitted": 1586344576.4784749, "started": 1586344576.4790802, "finished": 1586346680.3213403}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-50-29_xfo/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-50-29_xfo/referenceRealizedModeChoice.csv'\n"]
[[13, 0, 1], 20.0, {"submitted": 1586344431.595676, "started": 1586344431.5968714, "finished": 1586346722.2851284}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-51-23_hql/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-51-23_hql/referenceRealizedModeChoice.csv'\n"]
[[12, 0, 1], 6.666666666666666, {"submitted": 1586344391.4269917, "started": 1586344391.4283378, "finished": 1586346778.9935164}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-52-10_whe/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-52-10_whe/referenceRealizedModeChoice.csv'\n"]
[[11, 0, 1], 20.0, {"submitted": 1586344103.562744, "started": 1586344103.5636072, "finished": 1586346800.1070201}, {"loss": 146.9026179192056, "info": 146.9026179192056}, null]
[[14, 0, 0], 6.666666666666666, {"submitted": 1586344549.041412, "started": 1586344549.042557, "finished": 1586346939.3094418}, {"loss": 94.0, "info": 94.0}, null]
[[10, 0, 2], 6.666666666666666, {"submitted": 1586343967.0769002, "started": 1586343967.0788345, "finished": 1586347189.9839032}, {"loss": 194.92596366106298, "info": 194.92596366106298}, null]
[[15, 0, 0], 20.0, {"submitted": 1586345414.9688923, "started": 1586345414.970347, "finished": 1586347419.416495}, {"loss": 80.50135409614083, "info": 80.50135409614083}, null]
[[2, 0, 0], 20.0, {"submitted": 1586344870.5276258, "started": 1586344870.5283594, "finished": 1586347572.1060753}, {"loss": 159.1113935850176, "info": 159.1113935850176}, null]
[[16, 0, 0], 6.666666666666666, {"submitted": 1586345882.1139932, "started": 1586345882.1145065, "finished": 1586347857.4844704}, {"loss": 156.87982396750172, "info": 156.87982396750172}, null]
[[16, 0, 1], 6.666666666666666, {"submitted": 1586345985.2253551, "started": 1586345985.2259388, "finished": 1586348152.3955507}, {"loss": 156.10121868652675, "info": 156.10121868652675}, null]
[[4, 0, 2], 20.0, {"submitted": 1586345591.9514182, "started": 1586345591.9519815, "finished": 1586348186.793441}, {"loss": 195.4482173174873, "info": 195.4482173174873}, null]
[[0, 0, 1], 20.0, {"submitted": 1586344718.9693162, "started": 1586344718.970304, "finished": 1586348378.6529157}, {"loss": 195.4482173174873, "info": 195.4482173174873}, null]
[[14, 0, 2], 6.666666666666666, {"submitted": 1586344682.553979, "started": 1586344682.5547729, "finished": 1586348450.7596989}, {"loss": 194.9516573999406, "info": 194.9516573999406}, null]
[[6, 0, 1], 20.0, {"submitted": 1586345245.2601964, "started": 1586345245.261037, "finished": 1586348477.9918911}, {"loss": 178.99775338052646, "info": 178.99775338052646}, null]
[[17, 0, 1], 20.0, {"submitted": 1586346620.2920618, "started": 1586346620.3162432, "finished": 1586348606.040012}, {"loss": 127.78622207176709, "info": 127.78622207176709}, null]
[[12, 0, 0], 20.0, {"submitted": 1586346778.9995918, "started": 1586346779.001275, "finished": 1586348710.8320875}, {"loss": 133.41993906567365, "info": 133.41993906567365}, null]
[[18, 0, 0], 6.666666666666666, {"submitted": 1586346673.9581156, "started": 1586346673.9595814, "finished": 1586348833.775539}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-53-29_kzc/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-53-29_kzc/referenceRealizedModeChoice.csv'\n"]
[[8, 0, 2], 20.0, {"submitted": 1586346104.0392265, "started": 1586346104.0399218, "finished": 1586348851.6345468}, {"loss": 63.41305911726123, "info": 63.41305911726123}, null]
[[19, 0, 0], 20.0, {"submitted": 1586346800.4291863, "started": 1586346800.431465, "finished": 1586348908.3144822}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_12-27-41_dyc/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_12-27-41_dyc/referenceRealizedModeChoice.csv'\n"]
[[16, 0, 2], 6.666666666666666, {"submitted": 1586346477.0887263, "started": 1586346477.0938363, "finished": 1586348947.11952}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-37-57_eyz/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_11-37-57_eyz/referenceRealizedModeChoice.csv'\n"]
[[17, 0, 0], 20.0, {"submitted": 1586346480.558572, "started": 1586346480.559732, "finished": 1586348977.4097078}, {"loss": 182.59783344617466, "info": 182.59783344617466}, null]
[[10, 0, 1], 20.0, {"submitted": 1586347189.992263, "started": 1586347189.9933608, "finished": 1586349198.4218223}, {"loss": 195.45241531539182, "info": 195.45241531539182}, null]
[[15, 0, 1], 20.0, {"submitted": 1586345867.8058739, "started": 1586345867.8063762, "finished": 1586349205.786791}, {"loss": 92.55730489250043, "info": 92.55730489250043}, null]
[[18, 0, 2], 6.666666666666666, {"submitted": 1586346722.2944167, "started": 1586346722.2958102, "finished": 1586349209.129617}, null, "Traceback (most recent call last):\n  File \"/home/ubuntu/ksc_calibration/HpBandSter/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/ubuntu/ksc_calibration/BEAM_Optimizer/BeamWorker.py\", line 92, in compute\n    df = pd.read_csv(latest_subdir+\"/referenceRealizedModeChoice.csv\").iloc[[0, -1]].drop(['iterations'], axis=1)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 685, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 457, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 895, in __init__\n    self._make_engine(self.engine)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1135, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File \"/home/ubuntu/ksc_calibration/POST_PROCESSING/PY_CONDA_ENV/ENTER/envs/beamenv/lib/python3.7/site-packages/pandas/io/parsers.py\", line 1917, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n  File \"pandas/_libs/parsers.pyx\", line 689, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_12-33-28_iwb/referenceRealizedModeChoice.csv' does not exist: b'/home/ubuntu/ksc_calibration/beam/output/sf-light/urbansim-10k-xml__2020-04-08_12-33-28_iwb/referenceRealizedModeChoice.csv'\n"]
